- name: Install Base Packags
  apt:
    update_cache: "{{ update_apt_cache }}"
    state: present
    name:
      - locales
      - build-essential
      - acl
      - ntp
      - htop
      - git
      - "{{ base_python_package }}-pip"
      - "i{{ base_python_package }}"
      - supervisor
  tags:
    - packages

- name: Upgrade pip
  pip: name=pip state=latest
  tags:
    - packages