---

- name: restart celery worker
  supervisorctl: name=celery_worker state=restarted
  listen: restart celery worker

- name: restart celery beat
  supervisorctl: name=celery_beat state=restarted
  listen: restart celery beat
