# Generated by Django 2.1.8 on 2019-06-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='is_real',
            field=models.SmallIntegerField(default=1),
        ),
    ]
