# Generated by Django 2.1.8 on 2019-06-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_auto_20190611_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='is_real',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='country',
            name='livescore_id',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
