# Generated by Django 2.1.8 on 2019-06-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='livescore_country_id',
            field=models.CharField(max_length=250),
        ),
    ]
