# Generated by Django 2.1.8 on 2019-06-12 14:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_auto_20190612_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('livescore_id', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('livescore_league_id', models.CharField(max_length=250)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='football.League')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
