# Generated by Django 2.1.8 on 2019-06-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_auto_20190615_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='api_country_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='api_league_id',
        ),
    ]
