# Generated by Django 2.1.8 on 2019-06-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_auto_20190615_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_supported',
            field=models.BooleanField(default=False, verbose_name='Is league supported by KoraInbox?'),
        ),
        migrations.AddField(
            model_name='team',
            name='api_league_id',
            field=models.CharField(default=False, max_length=250),
            preserve_default=False,
        ),
    ]
