# Generated by Django 2.1.8 on 2019-06-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_auto_20190615_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='api_league_id',
        ),
    ]
