# Generated by Django 2.1.8 on 2019-06-15 16:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0010_remove_team_api_league_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='is_real',
            field=models.BooleanField(default='1', max_length=1),
        ),
    ]
