# Generated by Django 2.1.8 on 2019-06-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0011_auto_20190615_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='is_real',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
