# Generated by Django 2.1.8 on 2019-06-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0012_auto_20190615_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='api_id',
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default='aa', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
