# Generated by Django 2.1.8 on 2019-06-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0015_fixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_ar_eg',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
