# Generated by Django 2.1.8 on 2019-06-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0017_auto_20190621_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='name_ar_eg',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='league',
            name='name_ar_eg',
        ),
        migrations.RemoveField(
            model_name='league',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name_ar_eg',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name_en',
        ),
    ]
