# Generated by Django 2.1.8 on 2019-06-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0018_auto_20190621_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_ar',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='name_ar',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name_ar',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
