# Generated by Django 2.1.8 on 2019-10-01 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0019_auto_20190621_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueUserMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='football.League')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='followers',
            field=models.ManyToManyField(through='football.LeagueUserMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='leagueusermembership',
            unique_together={('user', 'league')},
        ),
    ]
