# Generated by Django 2.1.8 on 2019-10-01 12:59

import bakr_bot.football.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0020_auto_20191001_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='logo',
            field=models.FileField(default='default', upload_to=bakr_bot.football.utils.league_directory_path),
            preserve_default=False,
        ),
    ]
