# Generated by Django 2.1.8 on 2019-10-02 15:07

import bakr_bot.football.utils
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0021_league_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('api_id', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('name_ar', models.CharField(blank=True, max_length=250, null=True)),
                ('is_supported', models.BooleanField(default=False, verbose_name='Is competition supported by KoraInbox?')),
                ('logo', models.FileField(upload_to=bakr_bot.football.utils.competition_directory_path)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='football.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompetitionUserMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='football.Competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='league',
            name='country',
        ),
        migrations.RemoveField(
            model_name='league',
            name='followers',
        ),
        migrations.AlterUniqueTogether(
            name='leagueusermembership',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='leagueusermembership',
            name='league',
        ),
        migrations.RemoveField(
            model_name='leagueusermembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='league',
        ),
        migrations.RemoveField(
            model_name='team',
            name='league',
        ),
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='football.Country'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='League',
        ),
        migrations.DeleteModel(
            name='LeagueUserMembership',
        ),
        migrations.AddField(
            model_name='competition',
            name='followers',
            field=models.ManyToManyField(through='football.CompetitionUserMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixture',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='football.Competition'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='competitionusermembership',
            unique_together={('user', 'competition')},
        ),
    ]
