# Generated by Django 2.1.8 on 2019-10-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0022_auto_20191002_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='api_id',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
