# Generated by Django 2.1.8 on 2019-10-03 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0024_auto_20191003_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='football.Country'),
        ),
    ]
