# Generated by Django 2.1.8 on 2019-10-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0026_fixture_name_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='event_date',
            field=models.DateField(),
        ),
    ]
