# Generated by Django 2.1.8 on 2019-10-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0028_fixture_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='status',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
