# Generated by Django 2.1.8 on 2019-10-25 14:56

import bakr_bot.football.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0029_auto_20191004_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=bakr_bot.football.utils.fixture_directory_path),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=bakr_bot.football.utils.team_directory_path),
        ),
    ]
